addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml # because pip installation is slow
      - python-simplejson
      - python-serial

language: python

python:
  - "2.7"

virtualenv:
  system_site_packages: true

env:
  global:
  - VERSION="7.0" TESTS="0" LINT_CHECK="0" TRANSIFEX="0"
  - TRANSIFEX_USER='transbot@odoo-community.org'
  - secure: e1ll1txRZYe1nCku7PfGoCBfSE/tFtw0DOq8Dm+ivtn0tZ0rS4a2oOjiQJeaUVOImYRtlcNIikuJdMsgNRdELItONf5ETGCT5LYYJ95URGvTF+0I3MtGTXShxQ6wQInyy0zB3qvkKPpkh2YuTUIYqlV3/eGwNimA5PnyqX4vtWg=

  matrix:
  - LINT_CHECK="1"
  - TRANSIFEX="1"
  - TESTS="1" ODOO_REPO="odoo/odoo"
  - TESTS="1" ODOO_REPO="OCA/OCB"

install:
  - git clone https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly
  - apt-get install xfonts-75dpi
  - wget http://wkhtmltopdf.googlecode.com/files/wkhtmltopdf-0.11.0_rc1-static-amd64.tar.bz2
  - tar xf wkhtmltopdf-0.11.0_rc1-static-amd64.tar.bz2
  - export PATH=${HOME}:${PATH}

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
